OnlineLaptopStore/OnlineLaptopStore/Controllers/LaptopStoreController.cs
using OnlineLaptopStore.LaptopView;
using OnlineLaptopStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineLaptopStore.Controllers
{
    public class LaptopStoreController : Controller
    {
        private LaptopStoreEntities obj;
        private List<CartView> listofCartView;
        public  LaptopStoreController()
        {
            obj = new LaptopStoreEntities();
            listofCartView = new List<CartView>();
        }
        // GET: LaptopStore
        public ActionResult Index()
        {
            IEnumerable<LaptopStoreView> listofLaptopStoreView = (from OBJitem in obj.Items
                    join
                    objcat in obj.Categories
                    on OBJitem.Category_id equals objcat.Category_id
                    select new LaptopStoreView()
                    {
                        Image_path = OBJitem.Image_path,
                        Item_name = OBJitem.Item_name,
                        Description = OBJitem.Description,
                        Item_price = OBJitem.Item_price,
                        Item_id = OBJitem.Item_id,
                        Category = objcat.Category_name,
                        Item_code = OBJitem.Item_code,
                    }).ToList();
            return View(listofLaptopStoreView);
        }

        [HttpPost]
        public JsonResult Index(string Item_id) 
        {

            CartView objcartview = new CartView();
            Item objitem = obj.Items.Single(model => model.Item_id.ToString() == Item_id) ;
            if (Session["CartCounter"]!= null)
            {
                listofCartView = Session["CartItems"] as List<CartView>;
            }
            if(listofCartView.Any(model => model.Item_id == Item_id))
            {
                objcartview = listofCartView.Single(model => model.Item_id == Item_id);
                objcartview.Quantity = objcartview.Quantity + 1;
                objcartview.Total = objcartview.Quantity * objcartview.Unit_price;
            }
            else 
            { 
                objcartview.Item_id = Item_id;
                objcartview.Item_name = objitem.Item_name;
                objcartview.Image_path = objitem.Image_path;
                objcartview.Quantity = 1;
                objcartview.Total = objitem.Item_price;
                objcartview.Unit_price = objitem.Item_price;
                listofCartView.Add(objcartview);
            }

            Session["CartCounter"] = listofCartView.Count;
            Session["CartItems"] = listofCartView;
            return Json(new {Success = true, Counter = listofCartView.Count},JsonRequestBehavior.AllowGet);
        }

        public ActionResult Cart()
        {
            listofCartView = Session["CartItems"] as List<CartView>;
            return View(listofCartView);
        }

    }
}

OnlineLaptopStore/OnlineLaptopStore/Views/LaptopStore/Cart.cshtml
@model IEnumerable<OnlineLaptopStore.LaptopView.CartView>
@{
    ViewBag.Title = "Cart";
    decimal TotalAmount = 0.00M;
}

<h2>Cart</h2>

<table class="table-condensed" width="100%">
    @foreach(var item in Model)
            {
                TotalAmount += item.Total;
                <tr>
                    <td>
                        <img src="@Url.Content(item.Image_path)" class="img-responsive" height="200px" width="200px" />
                    </td>
                    <td>
                        @item.Item_name
                    </td>
                    <td style="text-align:right">
                        @item.Quantity.ToString("#,##0")
                    </td>
                    <td style="text-align:right">
                        @item.Unit_price.ToString("#,##0.00")
                    </td>
                    <td style="text-align:right">
                        @item.Total.ToString("#,##0.00")
                    </td>
                    
                </tr>
            }

    <tr style="border-top:1px solid Black" >
        <td colspan="4" style="text-align:right">
            <h3>Total Amount</h3>
        </td>
        <td style="text-align:right">
            <h3>@TotalAmount.ToString("#,##0.00")</h3>
        </td>
    </tr>
    <tr>
        
        <td >
            @Html.ActionLink("Back to Store","Index","LaptopStore")
        </td>
    </tr>

</table>

OnlineLaptopStore/OnlineLaptopStore/Views/LaptopStore/Index.cshtml
@model IEnumerable<OnlineLaptopStore.LaptopView.LaptopStoreView>
@{
    ViewBag.Title = "Index";
}

<head>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

</head>
<body style="background-color:lightgray">
<script type="text/javascript">
    function AddToCart(item) {
        var Item_Id = $(item).attr("Item_id");
        var Formdata = new FormData();
        Formdata.append("Item_id", Item_Id);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: Formdata,
            url: '/LaptopStore/Index',
            success: function (data) {
                if (data.Success) {
                    $("#cartitem").text("Cart(" + data.Counter + ")");
                }
            },
            error: function () {
                alert("An error occured")
            },
        });
    }

</script>

<div class="container">
    <h2 class="text-center">Laptop List</h2>
    @foreach (var item in Model)
    {

        <div class="row">
            <div class="card" style="border: 1px solid black; background-color: white; box-shadow: 10px 10px 5px -1px rgb(0 0 0 / 30%); ">
                <img class="img-responsive" src="@Url.Content(@item.Image_path)" height="200 px" width="200 px" style="margin-top: 10px; margin-left: 5px;" />

                <div class="card-body">
                    <h5 class="card-title" style=" margin-left:10px"><b>@item.Item_name  </b></h5>
                    <p class="card-text" style=" margin-left:10px"><b>Description: </b>  @item.Description</p>
                    <p class="card-text" style=" margin-left:10px"> <b>Price: </b> <span style="color:green;">@item.Item_price.ToString("#,##0.00 INR")</span> </p>

                    <input type="button" name="AddToCart" value="Add to Cart" class="btn btn-primary" Item_id="@item.Item_id" id="btnAddToCart" onclick="AddToCart(this)" style=" margin-left: 10px; margin-bottom: 10px;" />
                </div>
            </div>
        </div>

        <br />

    }

</div>

</body>